services:
  database:
    image: mariadb:11
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: Test1!
      MARIADB_DATABASE: diplomDB
      MARIADB_USER: max
      MARIADB_PASSWORD: Test1!

  backend:
    build:
      context: ./backend
    image: diplomarbeit-backend:latest
    restart: unless-stopped
    environment:
      BACKEND_PORT: 3000
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: diplomDB
      DB_USER: max
      DB_PASSWORD: Test1!
      JWT_SECRET: p1IS9nDdchqdixREMMyh4IVWDcyY7jUBogbpTEBuiBWo4qaloR5Vyqq1lLkU5zKqGS4P8XnjL4oZkgjbsTMDZS
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: Test1!
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    image: diplomarbeit-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
